lib/quick_note_web/router.ex
defmodule QuickNoteWeb.Router do
  use QuickNoteWeb, :router

  import QuickNoteWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {QuickNoteWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", QuickNoteWeb do
    pipe_through :browser

    get("/", PageController, :index)
  end

  # Other scopes may use custom stacks.
  # scope "/api", QuickNoteWeb do
  #   pipe_through :api
  # end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", QuickNoteWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", QuickNoteWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/profile", UserProfileController, :index
    delete "/users/profile", UserProfileController, :delete
    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    live "/users/folders", UserFoldersLive, :index
    live "/users/folders/new", UserFoldersLive, :new
    live "/users/folders/:folder_id", UserFolderDetailLive, :index
    live "/users/folders/:folder_id/new", UserFolderDetailLive, :new
    live "/users/folders/:folder_id/edit", UserFolderDetailLive, :edit
    live "/users/folders/:folder_id/delete", UserFolderDetailLive, :delete
    live "/users/folders/:folder_id/notes/:note_id", UserNoteLive, :index
    live "/users/folders/:folder_id/notes/:note_id/edit", UserNoteLive, :edit
    live "/users/folders/:folder_id/notes/:note_id/delete", UserNoteLive, :delete
  end

  scope "/", QuickNoteWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/quick_note_web/controllers/user_registration_controller.ex
defmodule QuickNoteWeb.UserRegistrationController do
  use QuickNoteWeb, :controller

  alias QuickNote.Accounts
  alias QuickNote.Accounts.User
  alias QuickNoteWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :edit, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/quick_note_web/views/user_registration_view.ex
defmodule QuickNoteWeb.UserRegistrationView do
  use QuickNoteWeb, :view
end

lib/quick_note_web/templates/user_registration/new.html.heex
<h2 class="font-semibold text-xl mb-4 font-heading">Register</h2>

<.form let={f} for={@changeset} action={Routes.user_registration_path(@conn, :create)}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="flex flex-col gap-y-4 drop-shadow-lg bg-white p-8 rounded-lg">
    <div class="flex flex-col gap-y-1">
      <%= label f, :name, class: "text-md" %>
      <%= text_input f, :name, required: true, class: "border-none bg-light rounded-md"  %>
      <%= error_tag f, :name %>
    </div>

    <div class="flex flex-col gap-y-1">
      <%= label f, :email %>
      <%= email_input f, :email, required: true, class: "border-none bg-light rounded-md"  %>
      <%= error_tag f, :email %>
    </div>

    <div class="flex flex-col gap-y-1">
      <%= label f, :email_confirmation %>
      <%= email_input f, :email_confirmation, required: true, class: "border-none bg-light rounded-md"  %>
      <%= error_tag f, :email_confirmation %>
    </div>

    <div class="flex flex-col gap-y-1">
      <%= label f, :password %>
      <%= password_input f, :password, required: true, class: "border-none bg-light rounded-md"  %>
      <%= error_tag f, :password %>
    </div>

      <%= submit "Register", class: "w-1/2 mx-auto bg-primary text-white py-2 rounded-md mt-4" %>
  </div>
</.form>

<%# <h1>Register</h1> %>
<%#

<%# <.form let={f} for={@changeset} action={Routes.user_registration_path(@conn, :create)}> %>
<%#   <%= if @changeset.action do %1> %>
<%#     <div class="alert alert-danger"> %>
<%#       <p>Oops, something went wrong! Please check the errors below.</p> %>
<%#     </div> %>
<%#   <% end %1> %>

<%#   <%= label f, :email %1> %>
<%#   <%= email_input f, :email, required: true %1> %>
<%#   <%= error_tag f, :email %1> %>

<%#   <%= label f, :password %1> %>
<%#   <%= password_input f, :password, required: true %1> %>
<%#   <%= error_tag f, :password %1> %>

<%#   <div> %>
<%#     <%= submit "Register" %1> %>
<%#   </div> %>
<%# </.form> %>

<%# <p> %>
<%#   <%= link "Log in", to: Routes.user_session_path(@conn, :new) %1> | %>
<%#   <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new) %1> %>
<%# </p> %>